// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"full-width full-height\" x-data=\"{ screenSize: window.innerWidth, selected:null }\" x-init=\"window.addEventListener(&#39;resize&#39;, () =&gt; screenSize = window.innerWidth)\"><div class=\"mobile-header full-width full-height\" x-show=\"screenSize &lt;= 425\" x-cloak><a class=\"full-height\" href=\"/\"><img class=\"full-height\" src=\"/static/images/logo.png\"></a> <button type=\"button\" class=\"accordian-button width-5\" @click=\"selected !== 1 ? selected = 1 : selected = null\"><div><div :class=\"{&#39;active&#39;: selected}\" class=\"toggle\"><div class=\"bar bar--top\" :style=\"selected ? &#39;bottom: calc(50% - 4px / 2); transform: rotate(135deg)&#39; : &#39;&#39;\"></div><div class=\"bar bar--middle\" :style=\"selected ? &#39;opacity: 0&#39; : &#39;&#39;\"></div><div class=\"bar bar--bottom\" :style=\"selected ? &#39;top: calc(50% - 4px / 2); transform: rotate(225deg)&#39; : &#39;&#39;\"></div></div></div></button><div class=\"overflow-container max-h-0\" x-ref=\"container1\" x-bind:style=\"selected == 1 ? {\n              &#39;max-height&#39;: $refs.container1.scrollHeight + &#39;px&#39;,\n              &#39;padding&#39;: &#39;1rem&#39;,\n              &#39;z-index&#39;: &#39;2&#39;\n            } : {}\"><div class=\"flex column justify-center align-center gap-1\"><a href=\"/\">Home</a> <a href=\"/services\">Services</a> <a href=\"/reviews\">Reviews</a> <a href=\"/contact-us\">Contact Us</a></div></div></div><div class=\"header full-width full-height\" x-show=\"screenSize &gt; 425\" x-cloak><a class=\"full-height\" href=\"/\"><img class=\"full-height\" src=\"/static/images/logo.png\"></a><div class=\"a-container full-height\"><a href=\"/\">Home</a> <a href=\"/services\">Services</a> <a href=\"/reviews\">Reviews</a> <a href=\"/contact-us\">Contact Us</a></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
