// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"section-prim full-width\"><h1>We Are Building a <span>Brighter Future</span></h1><p>Committed to helping your child achieve academic success</p></div><div class=\"section-alt card-container full-width\"><h1>Our Main Benefits</h1><div class=\"card full-width\"><h2>Many Years of Success</h2><p>Benefit from an outstanding track record of over 300 successful lessons taught to students across the world, averaging at 4.9 stars.</p></div><div class=\"card full-width\"><h2>Tailored Tutoring</h2><p>Each lesson is tailored to suit each student's individual needs, breaks down complex topics into simple, understandable steps, making learning both effective and enjoyable.</p></div><div class=\"card full-width\"><h2>Flexible Committment at Affordable Prices</h2><p>Experience the perfect balance of affordability and flexibility, making it easier than ever to provide your child with quality education, stress-free.</p></div></div><div class=\"section-prim flex column justify-center align-center full-width\"><h1>Make an Enquiry</h1><a class=\"flex row justify-center align-center pad-1 contact-button\" href=\"/contact-us\">Contact Us</a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
