// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContactUs() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"section-alt card-container full-width full-height\"><form id=\"form\" x-data=\"{ nameinput : $refs.nameinput}\" class=\"flex column align-center full-width form-container\" hx-post=\"/contact-us\" hx-target=\"form\" hx-swap=\"outerHTML\"><h2>Request a callback</h2><label :style=\"{ &#39;width&#39;: nameinput.offsetWidth + &#39;px&#39;}\" for=\"name\">Name</label> <input x-ref=\"nameinput\" type=\"text\" name=\"name\" value=\"\"> <label :style=\"{ &#39;width&#39;: nameinput.offsetWidth + &#39;px&#39;}\" for=\"number\">Number</label> <input x-ref=\"nameinput\" type=\"text\" name=\"number\" value=\"\"> <label :style=\"{ &#39;width&#39;: nameinput.offsetWidth + &#39;px&#39;}\" for=\"body\">Message</label> <textarea :style=\"{ &#39;width&#39;: nameinput.offsetWidth + &#39;px&#39;, &#39;min-height&#39;: &#39;4rem&#39;, &#39;margin-bottom&#39;: &#39;1rem&#39; }\" type=\"text\" name=\"body\" value=\"\"></textarea> <button class=\"submit-button\" type=\"submit\">Submit</button></form></div><div class=\"section-alt card-container full-width\"><div class=\"card-alt full-width\"><h2>Contact Details</h2><span>Email : mansimran2001@googlemail.com</span><br><br><span>Phone Number : 07495400251</span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
