# fly.toml app configuration file generated for src-sparkling-fog-6931 on 2025-02-17T18:16:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'src-sparkling-fog-6931'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
